#!/bin/sh
#
ls > tlist
count=0
while read line
do
  shfile[$count]=$(echo $line | awk '{print $1}')
  ((count++))
done<tlist



old_ver='metout="/lfs/h1/ops/prod/com/aqm/"+aqm_ver+"/"'
new_ver='metout="/lfs/h1/ops/prod/com/aqm/"+aqm_ver'

old_ver='"\/gpfs\/hps\/nco\/ops\/com\/aqm\/prod"'
new_ver='"\/lfs\/h1\/ops\/prod\/com\/aqm\/v6.1'
old_ver='\/gpfs\/hps\/ptmp\/Ho-Chun.Huang'
new_ver='\/lfs\/h2\/emc\/ptmp\/${USER}'
old_ver='/gpfs/dell2/emc/modeling/save'
new_ver='/lfs/h2/emc/physics/save'
old_ver='/gpfs/dell2/emc/verification/noscrub'
new_ver='/lfs/h2/emc/vpppg/noscrub'
old_ver='/gpfs/dell2/emc/verification'
new_ver='/lfs/h2/emc/vpppg'
old_ver='/gpfs/dell4/nco/ops/com/gefs/prod'
new_ver='/lfs/h1/ops/prod/com/gefs/v12.2'
old_ver='/gpfs/dell1/nco/ops/com/gfs/prod'
new_ver='/lfs/h1/ops/prod/com/gfs/v16.2'
old_ver='/gpfs/dell1/nco/ops/dcom/prod'
new_ver='/lfs/h1/ops/prod/dcom'
old_ver='/gpfs/dell2/stmp'
old_ver='/gpfs/dell1/stmp'
new_ver='/lfs/h2/emc/stmp'
old_ver='/gpfs/dell2/ptmp'
old_ver='/gpfs/dell1/ptmp'
new_ver='/lfs/h2/emc/ptmp'
old_ver='wgrib2=/gpfs/dell1/nco/ops/nwprod/grib_util.v1.1.1/exec/wgrib2'
new_ver='/apps/ops/prod/libs/intel/19.1.3.304/wgrib2/2.0.8/bin/wgrib2'
old_ver='wgrib=/gpfs/dell1/nco/ops/nwprod/grib_util.v1.1.1/exec/wgrib'
new_ver='wgrib=/apps/ops/prod/libs/intel/19.1.3.304/grib_util/1.2.2/bin/wgrib'
old_ver='/gpfs/dell3/ptmp/Lin.Gan'
new_ver='/lfs/h2/emc/ptmp/${USER}'

old_ver='"/gpfs/hps/nco/ops/com/aqm/",'
new_ver='"/lfs/h1/ops/prod/com/aqm/"+aqm_ver+"/",'
old_ver='data_dir="/gpfs/hps3/emc/meso/noscrub/"'
new_ver='data_dir="/lfs/h2/emc/physics/noscrub/"'
old_ver='"/gpfs/hps/nco/ops/com/aqm/"+envir'
new_ver='"/lfs/h1/ops/"+envir+"/com/aqm/"+aqm_ver+"/"'
old_ver='\/gpfs\/hps3\/emc\/meso\/noscrub\/Ho-Chun.Huang'
new_ver='\/lfs\/h2\/emc/\physics\/noscrub\/${USER}'
old_ver='\/gpfs\/hps3\/emc\/meso\/noscrub\/${USER}'
old_ver='\/gpfs\/hps3\/emc\/naqfc\/noscrub\/Ho-Chun.Huang'
old_ver='\/gpfs\/hps3\/emc\/naqfc\/noscrub\/${USER}'
old_ver='\/gpfs\/hps3\/emc\/meso\/noscrub\/Ho-Chun.Huang'
new_ver='\/lfs\/h2\/emc/\physics\/noscrub\/${USER}'
old_ver='\/gpfs\/hps\/nco\/ops\/com\/aqm\/${exp}'
new_ver='\/lfs\/h1\/ops\/${exp}\/com\/aqm\/v6.1'
old_ver='\/gpfs\/hps\/nco\/ops\/com\/${smlaqm}\/${exp2}'
new_ver='\/lfs\/h1\/ops\/${exp2}\/com\/${smlaqm}\/v6.1'
old_ver='\/gpfs\/hps\/nco\/ops\/com\/${smlaqm}\/${exp1}'
new_ver='\/lfs\/h1\/ops\/${exp1}\/com\/${smlaqm}\/v6.1'
old_ver='\/gpfs\/hps3\/emc\/${project'
old_ver='\/gpfs\/hps\/nco\/ops\/com\/aqm\/para'
old_ver='\/gpfs\/hps\/nco\/ops\/com\/aqm\/${exp1}'
new_ver='\/lfs\/h1\/ops\/${exp1}\/com\/aqm\/v6.1'
old_ver='\/gpfs\/hps\/nco\/ops\/com\/aqm\/${exp2}'
new_ver='\/lfs\/h1\/ops\/${exp2}\/com\/aqm\/v6.1'
old_ver='/gpfs/hps3/ptmp/${USER}'
old_ver='/gpfs/hps3/ptmp/Jianping.Huang'
old_ver='/gpfs/hps/ptmp/${USER}'
new_ver='/lfs/h2/emc/ptmp/${USER}'
old_ver='${COMROOThps}/aqm/${exp}'
new_ver='\/lfs\/h1\/ops\/${exp}\/com\/aqm\/v6.1'
old_ver='${COMROOThps}/${smlaqm}/${exp2}'
new_ver='\/lfs\/h1\/ops\/${exp2}\/com\/${smlaqm}\/v6.1'
old_ver='${COMROOThps}/aqm/para'
new_ver='\/lfs\/h1\/ops\/para\/com\/aqm\/v6.1'

old_ver='stmp_dir="/gpfs/dell2/stmp/"+user'
old_ver='stmp_dir="/gpfs/dell1/stmp/"+user'
new_ver='stmp_dir="/lfs/h2/emc/stmp/"+user'
old_ver='ptmp_dir="/gpfs/dell1/ptmp/"+user'
old_ver='ptmp_dir="/gpfs/dell2/ptmp/"+user'
new_ver='ptmp_dir="/lfs/h2/emc/ptmp/"+user'

old_ver='Ho-Chun.Huang'
new_ver='${USER}'
old_ver='/gpfs/dell2/emc/modeling/noscrub/${USER}'
new_ver='/lfs/h2/emc/physics/noscrub/${USER}'
old_ver='"/gpfs/dell2/ptmp/"+user'
old_ver='"/gpfs/dell1/ptmp/"+user'
new_ver='"/lfs/h2/emc/ptmp/"+user'
old_ver='"/gpfs/dell1/stmp/"+user'
old_ver='"/gpfs/dell2/stmp/"+user'
new_ver='"/lfs/h2/emc/stmp/"+user'

old_ver='/gpfs/dell1/stmp/${USER}'
old_ver='/gpfs/dell2/stmp/${USER}'
new_ver='/lfs/h2/emc/stmp/${USER}'
old_ver='/gpfs/dell2/ptmp/${USER}'
old_ver='/gpfs/dell1/ptmp/${USER}'
new_ver='/lfs/h2/emc/ptmp/${USER}'
old_ver='set proper stmp and ptmp location.  can not access /gpfs/dell1 and  /gpfs/dell3 on production machine'
new_ver='set proper stmp and ptmp location.'
old_ver='/gpfs/hps3/emc/meso/noscrub/${USER}'

old_ver='/gpfs/hps/stmp'
old_ver='/gpfs/hps3/stmp'
new_ver='/lfs/h2/emc/stmp'
old_ver='/gpfs/hps/ptmp'
old_ver='/gpfs/hps3/ptmp'
new_ver='/lfs/h2/emc/ptmp'
old_ver='/gpfs/hps3/emc/naqfc/noscrub/${USER}'
old_ver='/gpfs/hps3/emc/meso/noscrub/${USER}'
new_ver='/lfs/h2/emc/physics/noscrub/${USER}'
old_ver='"/gpfs/hps/nco/ops/com/aqm/"+envir'
new_ver='"/lfs/h1/ops/"+envir+"/com/aqm/"+aqm_ver'
old_ver='/gpfs/hps/nco/ops/com/aqm/prod'
new_ver='"/lfs/h1/ops/prod/com/aqm/"+aqm_ver'
old_ver='Jianping.Huang'
new_ver='jianping.huang'
old_ver='/5year/NCEPDEV/emc-naqfc/${USER}'
new_ver='/5year/NCEPDEV/emc-naqfc/Ho-Chun.Huang'
old_ver='BSUB -e'
new_ver='PBS -e'
old_ver='BSUB -W 04:30'
new_ver='PBS -l walltime="+task_cpu+"'
old_ver='BSUB -P CMAQ-T2O'
new_ver='PBS -A AQM-DEV'
old_ver='BSUB -R affinity\[core(1)\]'
new_ver=' '
old_ver='BSUB -q'
new_ver='PBS -q'
old_ver='BSUB -J'
new_ver='PBS -N'
old_ver='BSUB -n 1'
new_ver='PBS -l place=shared,select=1:ncpus=1:mem=4GB'
old_ver='BSUB -M 8000'
new_ver=' '
old_ver='bsub"'
new_ver='qsub"'
old_ver='metfilein=metout+"/aqm."+grdcro2d_date'
new_ver='metfilein=metout+"/cs."+grdcro2d_date'
old_ver='aqm."+date.strftime(YMD_date_format)'
new_ver='cs."+date.strftime(YMD_date_format)'
old_ver='AK."+date.strftime(YMD_date_format)'
new_ver='ak."+date.strftime(YMD_date_format)'
old_ver='HI."+date.strftime(YMD_date_format)'
new_ver='hi."+date.strftime(YMD_date_format)'
old_ver='metout=""\/lfs\/h1'
new_ver='metout="\/lfs\/h1'
old_ver='aqm\/"+aqm_ver"'
new_ver='aqm\/"+aqm_ver'
old_ver='"/lfs/h2/emc/physics/noscrub/${USER}/com/aqm/"+envir'
new_ver='"/lfs/h2/emc/physics/noscrub/"+user+"/com/aqm/"+envir'
old_ver='"/lfs/h2/emc/ptmp/${USER}/com/aqm/"+envir,'
new_ver='"/lfs/h2/emc/ptmp/"+user+"/com/aqm/"+envir,'
old_ver='"/lfs/h2/emc/ptmp/${USER}/com/aqm/"'
new_ver='"/lfs/h2/emc/ptmp/"+user+"/com/aqm/"'
old_ver='"/lfs/h2/emc/physics/noscrub/${USER}/com/aqm/"'
new_ver='"/lfs/h2/emc/physics/noscrub/"+user+"/com/aqm/"'
old_ver='/lfs/h2/emc/stmp/${USER}/'
new_ver='/lfs/h2/emc/stmp/"+user+"'
old_ver='figout="/lfs/h2/emc/stmp/"+user+""'
new_ver='figout="/lfs/h2/emc/stmp/"+user'
old_ver='""/lfs/h1/ops/prod/com/aqm/"+aqm_ver'
new_ver='"/lfs/h1/ops/prod/com/aqm/"+aqm_ver'
old_ver='figdir="/lfs/h2/emc/stmp/"+user+""'
new_ver='figdir="/lfs/h2/emc/stmp/"+user'
old_ver='aqm."+date.strftime(YMD_date_format)'
new_ver='cs."+date.strftime(YMD_date_format)'
old_ver='aqm."+sdate.strftime(YMD_date_format)'
new_ver='cs."+sdate.strftime(YMD_date_format)'
old_ver='\/AK.'
new_ver='\/ak.'
for i in "${shfile[@]}"
do
   echo ${i}
   if [ "${i}" == $0 ]; then continue; fi
   if [ "${i}" == "xtest1" ]; then continue; fi
   if [ -d ${i} ]; then continue; fi
   ## mv ${i}.bak ${i}
   if [ -e xtest1 ]; then /bin/rm -f xtest1; fi
   grep "${old_ver}" ${i} > xtest1
   if [ -s xtest1 ]; then
      mv ${i} ${i}.bak
      sed -e "s!${old_ver}!${new_ver}!" ${i}.bak > ${i}
      ## echo "diff ${i} ${i}.bak"
      chmod u+x ${i}
      diff ${i} ${i}.bak
   fi
done
/bin/rm xtest1 tlist
exit
